import { createHmac } from 'crypto';
import { NextApiRequest, NextApiResponse } from 'next';
import Anthropic from '@anthropic-ai/sdk';
import { Octokit } from '@octokit/rest';
import jwt from 'jsonwebtoken';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

// Verify GitHub webhook signature
function verifyGitHubWebhook(req: NextApiRequest): boolean {
  const signature = req.headers['x-hub-signature-256'] as string;
  if (!signature) return false;

  const hmac = createHmac(
    'sha256',
    process.env.GITHUB_WEBHOOK_SECRET || ''
  );
  const body = JSON.stringify(req.body);
  hmac.update(body);
  const hash = `sha256=${hmac.digest('hex')}`;

  return hash === signature;
}

// Generate GitHub App JWT
function generateGitHubJWT(): string {
  const payload = {
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + 600,
    iss: process.env.GITHUB_APP_ID,
  };
  
  const privateKey = (process.env.GITHUB_PRIVATE_KEY || '')
    .replace(/\\n/g, '\n');

  return jwt.sign(payload, privateKey, { algorithm: 'RS256' });
}

// Get installation access token
async function getInstallationToken(installationId: number): Promise<string> {
  const jwtToken = generateGitHubJWT();
  const octokit = new Octokit({ auth: jwtToken });

  const response = await octokit.apps.createInstallationAccessToken({
    installation_id: installationId,
  });

  return response.data.token;
}

// Fetch PR diff
async function getPRDiff(
  owner: string,
  repo: string,
  pullNumber: number,
  token: string
): Promise<string> {
  const octokit = new Octokit({ auth: token });

  const { data } = await octokit.pulls.get({
    owner,
    repo,
    pull_number: pullNumber,
  });

  // Fetch the actual diff
  const diffResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls/${pullNumber}.diff`,
    {
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/vnd.github.v3.diff',
      },
    }
  );

  return diffResponse.text();
}

// Analyze code with Claude
async function reviewCode(diff: string): Promise<string> {
  const message = await anthropic.messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 1500,
    messages: [
      {
        role: 'user',
        content: `You are an expert code reviewer. Analyze this git diff and provide constructive feedback.

Focus on:
- Security issues and vulnerabilities
- Performance problems or inefficiencies
- Code clarity and maintainability
- Best practices violations
- Test coverage gaps or missing tests

Be concise and actionable. Keep your response under 200 words. If the code looks good, mention that.

Format your response as:
1. Summary (1-2 sentences)
2. Issues found (bullet points, or "No issues found")
3. Suggestions (1-3 recommendations)

Diff:
\`\`\`diff
${diff}
\`\`\``,
      },
    ],
  });

  return message.content[0].type === 'text' ? message.content[0].text : '';
}

// Post review comment on PR
async function postReviewComment(
  owner: string,
  repo: string,
  pullNumber: number,
  review: string,
  token: string
): Promise<void> {
  const octokit = new Octokit({ auth: token });

  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: pullNumber,
    body: `## 🤖 Code Review Copilot

${review}

---
*This automated review was generated by [Code Review Copilot](https://github.com/apps/code-review-copilot). Please have a human review critical changes.*`,
  });
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Verify webhook signature
  if (!verifyGitHubWebhook(req)) {
    console.log('Webhook signature verification failed');
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const event = req.body;

  // Only handle PR opened/synchronize events
  if (event.action !== 'opened' && event.action !== 'synchronize') {
    return res.status(200).json({ message: 'Event ignored' });
  }

  try {
    const { pull_request: pr, repository, installation } = event;
    
    if (!pr || !repository || !installation) {
      return res.status(400).json({ error: 'Invalid webhook payload' });
    }

    const owner = repository.owner.login;
    const repo = repository.name;
    const pullNumber = pr.number;

    console.log(`Processing PR #${pullNumber} in ${owner}/${repo}`);

    // Skip if PR is from a fork or draft
    if (pr.draft) {
      return res.status(200).json({ message: 'Skipping draft PR' });
    }

    // Get access token
    const token = await getInstallationToken(installation.id);

    // Fetch diff
    const diff = await getPRDiff(owner, repo, pullNumber, token);

    // Skip if diff is too large (> 50KB)
    if (diff.length > 50000) {
      await postReviewComment(
        owner,
        repo,
        pullNumber,
        'This PR is quite large to review automatically. Consider breaking it into smaller PRs for better feedback.',
        token
      );
      return res.status(200).json({ message: 'PR too large' });
    }

    // Skip if no changes
    if (diff.length < 100) {
      return res.status(200).json({ message: 'No significant changes' });
    }

    // Review with Claude
    const review = await reviewCode(diff);

    // Post comment
    await postReviewComment(owner, repo, pullNumber, review, token);

    console.log(`Successfully reviewed PR #${pullNumber}`);
    return res.status(200).json({ success: true });
  } catch (error) {
    console.error('Error processing webhook:', error);
    
    if (error instanceof Error) {
      return res.status(500).json({ 
        error: 'Internal server error',
        message: error.message 
      });
    }
    
    return res.status(500).json({ error: 'Internal server error' });
  }
}
