import { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { action, pull_request } = req.body;

    if (action !== 'opened' && action !== 'synchronize') {
      return res.status(200).json({ message: 'Event ignored' });
    }

    if (!pull_request) {
      return res.status(200).json({ message: 'No PR data' });
    }

    const owner = pull_request.base.repo.owner.login;
    const repo = pull_request.base.repo.name;
    const prNumber = pull_request.number;
    const prTitle = pull_request.title;
    const prBody = pull_request.body || '';
    const diffUrl = pull_request.diff_url;

    console.log(`[Bot] Processing PR #${prNumber} in ${owner}/${repo}`);

    // Get PR diff
    let diff = '';
    try {
      const diffResponse = await fetch(diffUrl);
      diff = await diffResponse.text();
      console.log(`[Bot] Got diff: ${diff.length} bytes`);
    } catch (error) {
      console.error('[Bot] Failed to fetch diff:', error);
      return res.status(500).json({ error: 'Failed to fetch diff' });
    }

    // Truncate diff if too long
    const truncatedDiff = diff.substring(0, 3000);

    // Call Claude API with better prompt
    let review = '';
    try {
      console.log('[Bot] Calling Claude API...');
      
      const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': process.env.ANTHROPIC_API_KEY || '',
          'anthropic-version': '2023-06-01',
        },
        body: JSON.stringify({
          model: 'claude-opus-4-6',
          max_tokens: 1500,
          messages: [
            {
              role: 'user',
              content: `You are an expert code reviewer. Review this GitHub PR and provide detailed feedback.

**PR Title:** ${prTitle}
**PR Description:** ${prBody}

**Code Changes:**
\`\`\`
${truncatedDiff}
\`\`\`

Please provide a thorough review covering:
1. **Security Issues** (if any) - e.g., SQL injection, hardcoded secrets
2. **Performance Issues** (if any) - e.g., N+1 queries, inefficient algorithms
3. **Code Quality** (if any) - e.g., error handling, naming, complexity
4. **Best Practices** (if any) - improvements or suggestions

Format your response clearly with headers for each category. Be specific and actionable.`,
            },
          ],
        }),
      });

      const claudeData = await claudeResponse.json();
      
      if (!claudeResponse.ok) {
        console.error('[Bot] Claude API error:', claudeData);
        review = '⚠️ Unable to generate review - Claude API error';
      } else {
        review = claudeData.content[0]?.text || '⚠️ Unable to generate review';
        console.log('[Bot] Got review from Claude');
      }
    } catch (error) {
      console.error('[Bot] Claude API exception:', error);
      review = '⚠️ Unable to generate review - error contacting Claude API';
    }

    // Post comment to GitHub PR
    try {
      console.log('[Bot] Posting comment to GitHub...');
      
      const commentBody = `## 🤖 Code Review Copilot

${review}

---
*Generated by Code Review Copilot powered by Claude AI*`;

      const commentResponse = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`,
        {
          method: 'POST',
          headers: {
            'Authorization': `token ${process.env.GITHUB_TOKEN || ''}`,
            'Content-Type': 'application/json',
            'Accept': 'application/vnd.github.v3+json',
          },
          body: JSON.stringify({
            body: commentBody,
          }),
        }
      );

      if (!commentResponse.ok) {
        const errorData = await commentResponse.text();
        console.error('[Bot] GitHub API error:', commentResponse.status, errorData);
        return res.status(500).json({ error: 'Failed to post comment', details: errorData });
      }

      console.log('[Bot] ✅ Review posted successfully');
      return res.status(200).json({ message: 'Review posted successfully' });
    } catch (error) {
      console.error('[Bot] Comment post exception:', error);
      return res.status(500).json({ error: 'Failed to post comment', details: String(error) });
    }
  } catch (error) {
    console.error('[Bot] Webhook error:', error);
    return res.status(500).json({ error: 'Internal server error', details: String(error) });
  }
}